[profile.default]
src = "src"
out = "out"
libs = ["lib"]


remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts']

# here we told to remap @chainlink/contracts/ to lib/chainlink-brownie-contracts/contracts now understand the syntax